export const filters = {
  make: [
    "Acura",
    "Alfa Romeo",
    "Aston Martin",
    "Audi",
    "BMW",
    "Bentley",
    "Buick",
    "Cadillac",
    "Chevrolet",
    "Chrysler",
    "Daewoo",
    "Dodge",
    "FIAT",
    "Ferrari",
    "Fisker",
    "Ford",
    "Freightliner",
    "GMC",
    "Genesis",
    "HUMMER",
    "Honda",
    "Hyundai",
    "INEOS",
    "INFINITI",
    "Isuzu",
    "Jaguar",
    "Jeep",
    "Kia",
    "Lamborghini",
    "Land Rover",
    "Lexus",
    "Lincoln",
    "Lotus",
    "Lucid",
    "MAZDA",
    "MINI",
    "Maserati",
    "Maybach",
    "McLaren",
    "Mercedes-Benz",
    "Mercury",
    "Mitsubishi",
    "Nissan",
    "Oldsmobile",
    "Panoz",
    "Plymouth",
    "Polestar",
    "Pontiac",
    "Porsche",
    "Ram",
    "Rivian",
    "Rolls-Royce",
    "SRT",
    "Saab",
    "Saturn",
    "Scion",
    "Subaru",
    "Suzuki",
    "Tesla",
    "Toyota",
    "Volkswagen",
    "Volvo",
    "smart",
  ],
  year: [
    "2024",
    "2023",
    "2022",
    "2021",
    "2020",
    "2019",
    "2018",
    "2017",
    "2016",
    "2015",
    "2014",
    "2013",
    "2012",
    "2011",
    "2010",
    "2009",
    "2008",
    "2007",
    "2006",
    "2005",
    "2004",
    "2003",
    "2002",
    "2001",
    "2000",
  ],
  model: [
    "1 Series",
    "124 Spider",
    "1500",
    "1500 Classic",
    "2 Series",
    "200",
    "2025-03-09 00:00:00",
    "2025-05-09 00:00:00",
    "2500",
    "2500 HD",
    "296 GTB",
    "296 GTS",
    "3 Series",
    "300",
    "300M",
    "3500",
    "350Z",
    "370Z",
    "4 Series",
    "430 Scuderia",
    "458 Italia",
    "458 Speciale",
    "458 Spider",
    "488 GTB",
    "488 Pista",
    "488 Spider",
    "4C",
    "4C Spider",
    "4Runner",
    "5 Series",
    "500",
    "500 Abarth",
    "500L",
    "500X",
    "500c",
    "500c Abarth",
    "500e",
    "57",
    "570GT",
    "570S",
    "599 GTB Fiorano",
    "599 GTO",
    "6 Series",
    "600LT",
    "612 Scaglietti",
    "62",
    "626",
    "650S",
    "675LT",
    "7 Series",
    "718 Boxster",
    "718 Cayman",
    "718 Spyder",
    "720S",
    "750S",
    "765LT",
    "8 Series",
    "812 GTS",
    "812 Superfast",
    "86",
    "9-2X",
    "9-4X",
    "9-7X",
    "911",
    "918 Spyder",
    "A",
    "A3",
    "A3 e-tron",
    "A4",
    "A4 (2005.5)",
    "A4 allroad",
    "A5",
    "A5 Sport",
    "A6",
    "A6 allroad",
    "A7",
    "A8",
    "AMG A",
    "AMG C",
    "AMG CLA",
    "AMG CLE",
    "AMG CLS",
    "AMG E",
    "AMG EQ",
    "AMG EQS",
    "AMG G",
    "AMG GLA",
    "AMG GLB",
    "AMG GLC",
    "AMG GLC Coupe",
    "AMG GLE",
    "AMG GLE Coupe",
    "AMG GLS",
    "AMG GT",
    "AMG S",
    "AMG SL",
    "AMG SLC",
    "AMG SLK",
    "ATS",
    "ATS-V",
    "Acadia",
    "Acadia Limited",
    "Accent",
    "Accord",
    "Accord Crosstour",
    "Accord Hybrid",
    "Aerio",
    "Air",
    "Alero",
    "Alpina B7",
    "Altima",
    "Amanti",
    "Amigo",
    "Ariya",
    "Armada",
    "Arnage",
    "Arteon",
    "Artura",
    "Ascender",
    "Ascent",
    "Aspen",
    "Astra",
    "Astro Cargo",
    "Astro Passenger",
    "Atlas",
    "Atlas Cross Sport",
    "Aura",
    "Aurora",
    "Avalanche",
    "Avalanche 1500",
    "Avalanche 2500",
    "Avalon",
    "Avalon Hybrid",
    "Avenger",
    "Aventador",
    "Aveo",
    "Aviator",
    "Axiom",
    "Azera",
    "Aztek",
    "Azure",
    "Azure T",
    "B",
    "B-Series",
    "B9 Tribeca",
    "BRZ",
    "Baja",
    "Base",
    "Beetle",
    "Bentayga",
    "Bentayga EWB",
    "Blackwood",
    "Blazer",
    "Bolt EUV",
    "Bolt EV",
    "Bonneville",
    "Borrego",
    "Boxster",
    "Bravada",
    "Breeze",
    "Bronco",
    "Bronco Sport",
    "Brooklands",
    "C",
    "C-HR",
    "C-MAX Energi",
    "C-MAX Hybrid",
    "C/V",
    "C/V Tradesman",
    "C30",
    "C40 Recharge",
    "C70",
    "CC",
    "CL",
    "CLA",
    "CLE",
    "CLK",
    "CLS",
    "CR-V",
    "CR-V Hybrid",
    "CR-Z",
    "CT",
    "CT4",
    "CT5",
    "CT6",
    "CT6-V",
    "CTS",
    "CTS-V",
    "CX-3",
    "CX-30",
    "CX-5",
    "CX-50",
    "CX-7",
    "CX-9",
    "CX-90",
    "CX-90 PHEV",
    "Cabrio",
    "Cadenza",
    "Caliber",
    "California",
    "Camaro",
    "Camry",
    "Camry Hybrid",
    "Canyon",
    "Captiva Sport",
    "Cara",
    "Carnival",
    "Carrera GT",
    "Cascada",
    "Catera",
    "Cavalier",
    "Cayenne",
    "Cayman",
    "Celica",
    "Century",
    "Challenger",
    "Charger",
    "Cherokee",
    "Cirrus",
    "City Express",
    "Civic",
    "Civic Type R",
    "Clarity Plug-in Hybrid",
    "Classic",
    "Clubman",
    "Cobalt",
    "Colorado",
    "Commander",
    "Compass",
    "Concorde",
    "Continental",
    "Continental GT",
    "Continental GTC",
    "Contour",
    "Convertible",
    "Cooper",
    "Corolla",
    "Corolla Cross",
    "Corolla Cross Hybrid",
    "Corolla Hatchback",
    "Corolla Hybrid",
    "Corolla iM",
    "Corsair",
    "Corvette",
    "Cougar",
    "Countryman",
    "Crossfire",
    "Crosstour",
    "Crosstrek",
    "Crown",
    "Crown Victoria",
    "Cruze",
    "Cruze Limited",
    "Cullinan",
    "Cybertruck",
    "DB11",
    "DB12",
    "DB9",
    "DB9 GT",
    "DBS",
    "DBS Superleggera",
    "DBX",
    "DTS",
    "Dakota",
    "Dart",
    "Dawn",
    "DeVille",
    "Defender 110",
    "Defender 130",
    "Defender 90",
    "Diamante",
    "Discovery",
    "Discovery Series II",
    "Discovery Sport",
    "Durango",
    "E",
    "E-PACE",
    "E-Transit 350 Cargo",
    "E150 Cargo",
    "E150 Passenger",
    "E150 Super Duty Cargo",
    "E150 Super Duty Passenger",
    "E250 Cargo",
    "E250 Super Duty Cargo",
    "E350 Super Duty Cargo",
    "E350 Super Duty Passenger",
    "ELR",
    "EQ EQB",
    "EQ EQE",
    "EQ EQE SUV",
    "EQ EQS",
    "EQ EQS SUV",
    "ES",
    "EV6",
    "EV9",
    "EX",
    "Echo",
    "Eclipse",
    "Eclipse Cross",
    "EcoSport",
    "Econoline E150 Cargo",
    "Econoline E150 Passenger",
    "Econoline E250 Cargo",
    "Econoline E350 Super Duty Cargo",
    "Econoline E350 Super Duty Passenger",
    "Edge",
    "Elantra",
    "Elantra GT",
    "Elantra Hybrid",
    "Elantra N",
    "Eldorado",
    "Electrified G80",
    "Electrified GV70",
    "Element",
    "Elise",
    "Enclave",
    "Encore",
    "Encore GX",
    "Endeavor",
    "Entourage",
    "Envision",
    "Envista",
    "Envoy",
    "Envoy XL",
    "Envoy XUV",
    "Eos",
    "Equator",
    "Equinox",
    "Equus",
    "Escalade",
    "Escalade ESV",
    "Escalade EXT",
    "Escape",
    "Escape Plug-in Hybrid",
    "Escort",
    "Esperante",
    "Esteem",
    "Euro",
    "Evora",
    "Evora 400",
    "Evora GT",
    "Excursion",
    "Exige",
    "Exige S",
    "Expedition",
    "Expedition EL",
    "Expedition MAX",
    "Explorer",
    "Explorer Sport",
    "Explorer Sport Trac",
    "Express 1500 Cargo",
    "Express 1500 Passenger",
    "Express 2500 Cargo",
    "Express 2500 Passenger",
    "Express 3500 Cargo",
    "Express 3500 Passenger",
    "F-PACE",
    "F-TYPE",
    "F12berlinetta",
    "F150",
    "F150 (Heritage)",
    "F150 Lightning",
    "F250 Super Duty",
    "F350 Super Duty",
    "F430",
    "F450 Super Duty",
    "F8",
    "FF",
    "FJ Cruiser",
    "FR-S",
    "FX",
    "Fiesta",
    "Firebird",
    "Fit",
    "Five Hundred",
    "Flex",
    "Flying Spur",
    "Focus",
    "Focus ST",
    "Forenza",
    "Forester",
    "Forte",
    "Forte Koup",
    "Forte5",
    "Freelander",
    "Freestar",
    "Freestyle",
    "Frontier",
    "Fusion",
    "Fusion Energi",
    "Fusion Plug-in Hybrid",
    "G",
    "G3",
    "G5",
    "G6",
    "G6 (2009.5)",
    "G70",
    "G8",
    "G80",
    "G90",
    "GL",
    "GLA",
    "GLB",
    "GLC",
    "GLC Coupe",
    "GLE",
    "GLE Coupe",
    "GLI",
    "GLK",
    "GLS",
    "GR 86",
    "GR Corolla",
    "GR Supra",
    "GS",
    "GT",
    "GT-R",
    "GTC4Lusso",
    "GTI",
    "GTO",
    "GV60",
    "GV70",
    "GV80",
    "GX",
    "Galant",
    "Gallardo",
    "Genesis",
    "Ghibli",
    "Ghost",
    "Giulia",
    "Gladiator",
    "Golf",
    "Golf Alltrack",
    "Golf GTI",
    "Golf R",
    "Golf SportWagen",
    "GranSport",
    "GranTurismo",
    "Grand Am",
    "Grand Cherokee",
    "Grand Cherokee 4xe",
    "Grand Cherokee L",
    "Grand Highlander",
    "Grand Highlander Hybrid",
    "Grand Marquis",
    "Grand Prix",
    "Grand Vitara",
    "Grand Voyager",
    "Grand Wagoneer",
    "Grand Wagoneer L",
    "Grecale",
    "Grenadier",
    "H1",
    "H2",
    "H3",
    "H3T",
    "HHR",
    "HR-V",
    "HS",
    "HUMMER EV",
    "Hardtop",
    "Highlander",
    "Highlander Hybrid",
    "Hombre",
    "Hornet",
    "Huracan",
    "I",
    "I-PACE",
    "ID.4",
    "ILX",
    "IONIQ 5",
    "IONIQ 6",
    "IS",
    "IS F",
    "Impala",
    "Impala Limited",
    "Impreza",
    "Insight",
    "Integra",
    "Intrepid",
    "Intrigue",
    "Ion",
    "Ioniq Electric",
    "Ioniq Hybrid",
    "Ioniq Plug-in Hybrid",
    "JUKE",
    "JX",
    "Jetta",
    "Jetta (New)",
    "Jetta GLI",
    "Jetta SportWagen",
    "Jimmy",
    "Journey",
    "K5",
    "K900",
    "Karma",
    "Kicks",
    "Kizashi",
    "Kona",
    "Kona Electric",
    "Kona N",
    "L-Series",
    "LC",
    "LEAF",
    "LFA",
    "LHS",
    "LR2",
    "LR3",
    "LR4",
    "LS",
    "LX",
    "LYRIQ",
    "LaCrosse",
    "Lancer",
    "Lancer Evolution",
    "Land Cruiser",
    "Lanos",
    "LeSabre",
    "Legacy",
    "Leganza",
    "Levante",
    "Liberty",
    "Lucerne",
    "Lumina",
    "M",
    "M2",
    "M3",
    "M4",
    "M5",
    "M6",
    "M8",
    "MAZDA2",
    "MAZDA3",
    "MAZDA5",
    "MAZDA6",
    "MC20",
    "MDX",
    "MDX Hybrid",
    "MKC",
    "MKS",
    "MKT",
    "MKX",
    "MKZ",
    "MP4-12C",
    "MPV",
    "MR 2",
    "MX-30",
    "MX-5 Miata",
    "MX-5 Miata RF",
    "Macan",
    "Magnum",
    "Malibu",
    "Malibu (Classic)",
    "Malibu Limited",
    "Marauder",
    "Mariner",
    "Mark LT",
    "Matrix",
    "Maverick",
    "Maxima",
    "Maybach GLS",
    "Maybach S",
    "Maybach S 600",
    "Metris",
    "Metris WORKER",
    "Metro",
    "Milan",
    "Millenia",
    "Mirage",
    "Mirage G4",
    "Mirai",
    "Model 3",
    "Model S",
    "Model X",
    "Model Y",
    "Montana",
    "Montana SV6",
    "Monte Carlo",
    "Montego",
    "Monterey",
    "Montero",
    "Montero Sport",
    "Mountaineer",
    "Mulsanne",
    "Murano",
    "Murcielago",
    "Murcielago LP640",
    "Mustang",
    "Mustang MACH-E",
    "Mystique",
    "NEXO",
    "NSX",
    "NV1500",
    "NV200",
    "NV200 Taxi",
    "NV2500 HD",
    "NV3500 HD",
    "NX",
    "Nautilus",
    "Navigator",
    "Navigator L",
    "Neon",
    "New Beetle",
    "Niro",
    "Niro EV",
    "Niro Plug-in Hybrid",
    "Nitro",
    "Nubira",
    "Ocean",
    "Odyssey",
    "Optima",
    "Optima (2006.5)",
    "Optima Hybrid",
    "Optima Plug-in Hybrid",
    "Outback",
    "Outlander",
    "Outlander PHEV",
    "Outlander Sport",
    "Outlook",
    "P1",
    "PT Cruiser",
    "Paceman",
    "Pacifica",
    "Pacifica Hybrid",
    "Palisade",
    "Panamera",
    "Park Avenue",
    "Passat",
    "Passat (New)",
    "Passport",
    "Pathfinder",
    "Pathfinder Armada",
    "Patriot",
    "Phaeton",
    "Phantom",
    "Pilot",
    "Portofino",
    "Portofino M",
    "Prelude",
    "Prius",
    "Prius Plug-in Hybrid",
    "Prius Prime",
    "Prius c",
    "Prius v",
    "Prizm",
    "ProMaster 1500 Cargo",
    "ProMaster 2500 Cargo",
    "ProMaster 3500 Cargo",
    "ProMaster Cargo",
    "ProMaster City",
    "ProMaster Window",
    "Protege",
    "Protege5",
    "Prowler",
    "Q",
    "Q3",
    "Q4 e-tron",
    "Q40",
    "Q5",
    "Q50",
    "Q60",
    "Q7",
    "Q70",
    "Q8",
    "Q8 e-tron",
    "QX",
    "QX30",
    "QX50",
    "QX55",
    "QX60",
    "QX70",
    "QX80",
    "Quattroporte",
    "Quest",
    "R",
    "R1S",
    "R1T",
    "R32",
    "R8",
    "RAV4",
    "RAV4 Hybrid",
    "RAV4 Prime",
    "RC",
    "RDX",
    "RL",
    "RLX",
    "RLX Hybrid",
    "RS 3",
    "RS 4",
    "RS 5",
    "RS 6",
    "RS 7",
    "RS Q8",
    "RS e-tron GT",
    "RSX",
    "RX",
    "RX-8",
    "RZ",
    "Rabbit",
    "Raider",
    "Rainier",
    "Ram 1500",
    "Ram 2500",
    "Ram 3500",
    "Ram Van 1500",
    "Ram Van 2500",
    "Ram Van 3500",
    "Ram Wagon 1500",
    "Ram Wagon 2500",
    "Ram Wagon 3500",
    "Range Rover",
    "Range Rover Evoque",
    "Range Rover Sport",
    "Range Rover Velar",
    "Ranger",
    "Rapide",
    "Rapide S",
    "Regal",
    "Regal TourX",
    "Relay",
    "Rendezvous",
    "Renegade",
    "Reno",
    "Ridgeline",
    "Rio",
    "Roadster",
    "Rodeo",
    "Rodeo Sport",
    "Rogue",
    "Rogue Select",
    "Rogue Sport",
    "Roma",
    "Rondo",
    "Routan",
    "S",
    "S-Series",
    "S-Type",
    "S10",
    "S2000",
    "S3",
    "S4",
    "S4 (2005.5)",
    "S40",
    "S40 (New)",
    "S5",
    "S6",
    "S60",
    "S7",
    "S70",
    "S8",
    "S80",
    "S90",
    "SC",
    "SF90",
    "SKY",
    "SL",
    "SLC",
    "SLK",
    "SLR McLaren",
    "SLS",
    "SQ5",
    "SQ7",
    "SQ8",
    "SRX",
    "SS",
    "SSR",
    "STS",
    "SX4",
    "Sable",
    "Safari",
    "Santa Cruz",
    "Santa Fe",
    "Santa Fe Hybrid",
    "Santa Fe Plug-in Hybrid",
    "Santa Fe Sport",
    "Santa Fe XL",
    "Savana 1500 Cargo",
    "Savana 1500 Passenger",
    "Savana 2500 Cargo",
    "Savana 2500 Passenger",
    "Savana 3500 Cargo",
    "Savana 3500 Passenger",
    "Sebring",
    "Sedona",
    "Seltos",
    "Sentra",
    "Sephia",
    "Sequoia",
    "Seville",
    "Sienna",
    "Sierra (Classic) 1500",
    "Sierra (Classic) 1500 HD",
    "Sierra (Classic) 2500",
    "Sierra (Classic) 2500 HD",
    "Sierra (Classic) 3500",
    "Sierra 1500",
    "Sierra 1500 HD",
    "Sierra 1500 Limited",
    "Sierra 2500",
    "Sierra 2500 HD",
    "Sierra 3500",
    "Sierra 3500 HD",
    "Silhouette",
    "Silverado (Classic) 1500",
    "Silverado (Classic) 1500 HD",
    "Silverado (Classic) 2500 HD",
    "Silverado (Classic) 3500",
    "Silverado 1500",
    "Silverado 1500 HD",
    "Silverado 1500 Limited",
    "Silverado 2500",
    "Silverado 2500 HD",
    "Silverado 3500",
    "Silverado 3500 HD",
    "Silverado EV",
    "Solara",
    "Solstice",
    "Solterra",
    "Sonata",
    "Sonata Hybrid",
    "Sonata Plug-in Hybrid",
    "Sonic",
    "Sonoma",
    "Sorento",
    "Sorento Hybrid",
    "Sorento Plug-in Hybrid",
    "Soul",
    "Soul EV",
    "Spark",
    "Spark EV",
    "Spectra",
    "Sportage",
    "Sportage Hybrid",
    "Sportage Plug-in Hybrid",
    "Sprinter 1500 Cargo",
    "Sprinter 1500 Passenger",
    "Sprinter 2500",
    "Sprinter 2500 Cargo",
    "Sprinter 2500 Passenger",
    "Sprinter 3500",
    "Sprinter 3500 Cargo",
    "Sprinter 3500 XD",
    "Sprinter 3500 XD Cargo",
    "Sprinter 4500",
    "Sprinter 4500 Cargo",
    "Sprinter WORKER Cargo",
    "Sprinter WORKER Passenger",
    "Spyder",
    "Stelvio",
    "Stinger",
    "Stratus",
    "Suburban",
    "Suburban 1500",
    "Suburban 2500",
    "Suburban 3500 HD",
    "Sunfire",
    "Swift",
    "TITAN",
    "TITAN XD",
    "TL",
    "TLX",
    "TSX",
    "TT",
    "TX",
    "Tacoma",
    "Tahoe",
    "Tahoe (New)",
    "Taos",
    "Taurus",
    "Taurus X",
    "Taycan",
    "Taycan Cross Turismo",
    "Taycan Sport Turismo",
    "Telluride",
    "Terrain",
    "Terraza",
    "Thunderbird",
    "Tiburon",
    "Tiguan",
    "Tiguan Limited",
    "Titan",
    "Torrent",
    "Touareg",
    "Touareg 2",
    "Town & Country",
    "Town Car",
    "Tracker",
    "Trailblazer",
    "Transit 150",
    "Transit 250",
    "Transit 350",
    "Transit 350 HD",
    "Transit 350 Passenger",
    "Transit Connect Cargo",
    "Transit Connect Passenger",
    "Traverse",
    "Trax",
    "Tribeca",
    "Tribute",
    "Trooper",
    "Tucson",
    "Tucson Hybrid",
    "Tucson Plug-in Hybrid",
    "Tundra",
    "Tundra Hybrid",
    "UX",
    "Uplander",
    "Urus",
    "V40",
    "V50",
    "V60",
    "V70",
    "V90",
    "VUE",
    "VehiCROSS",
    "Veloster",
    "Venture",
    "Venue",
    "Venza",
    "Veracruz",
    "Verano",
    "Verona",
    "Versa",
    "Versa Note",
    "Vibe",
    "Villager",
    "Viper",
    "Virage",
    "Vitara",
    "Volt",
    "Voyager",
    "WRX",
    "Wagoneer",
    "Wagoneer L",
    "Windstar",
    "Wraith",
    "Wrangler",
    "Wrangler 4xe",
    "Wrangler Unlimited",
    "Wrangler Unlimited 4xe",
    "X-Type",
    "X1",
    "X2",
    "X3",
    "X3 M",
    "X4",
    "X4 M",
    "X5",
    "X5 M",
    "X6",
    "X6 M",
    "X7",
    "XC40",
    "XC40 Recharge",
    "XC60",
    "XC70",
    "XC90",
    "XE",
    "XF",
    "XG300",
    "XG350",
    "XJ",
    "XK",
    "XL-7",
    "XL7",
    "XLR",
    "XM",
    "XT4",
    "XT5",
    "XT6",
    "XTS",
    "XV Crosstrek",
    "Xterra",
    "Yaris",
    "Yaris iA",
    "Yukon",
    "Yukon Denali",
    "Yukon XL",
    "Yukon XL 1500",
    "Yukon XL 2500",
    "Z",
    "Z3",
    "Z4",
    "Z4 M",
    "Z8",
    "ZDX",
    "ZX2",
    "Zephyr",
    "allroad",
    "bZ4X",
    "cube",
    "e-Golf",
    "e-tron",
    "e-tron GT",
    "e-tron S",
    "eSprinter",
    "fortwo",
    "fortwo EQ",
    "fortwo EQ cabrio",
    "fortwo cabrio",
    "fortwo electric drive",
    "fortwo electric drive cabrio",
    "i-280",
    "i-290",
    "i-350",
    "i-370",
    "i-MiEV",
    "i3",
    "i4",
    "i5",
    "i7",
    "i8",
    "iA",
    "iM",
    "iQ",
    "iX",
    "quish",
    "quish S",
    "tC",
    "tage",
    "xA",
    "xB",
    "xD",
  ],
};
